# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      milestone:
        description: 'The milestone you wanna filter'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # or one-off:
      - run: npm install node-fetch@2
      - uses: actions/github-script@v6
        with:
          script: |

            const fetch = require('node-fetch')
            let data = {
                text: "123"
            };
          
            fetch("https://hooks.slack.com/services/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", {
              method: "POST",
              body: JSON.parse(JSON.stringify(data)),
              headers: {'Content-Type': 'application/json'}
            }).then(res => {
              console.log("Request complete! response:", res);
            });
